# Generated by Django 4.1.3 on 2022-11-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eployee_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('o', 'OTHERS')], default='M', max_length=1)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField(max_length=11)),
                ('department', models.CharField(choices=[('T', 'TECHNICAL'), ('N', 'NON_TECHNICAL')], max_length=10)),
                ('position', models.CharField(choices=[('CO', 'COMPUTER_OPERATOR'), ('FS', 'FULL_STACK_SENIOR'), ('FJ', 'FULL_STACK_JUNIOR'), ('OT', 'OTHERS')], max_length=10)),
                ('date_hired', models.DateField()),
                ('monthly_salary', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'ACTIVE'), ('D', 'DEACTIVe')], max_length=10)),
            ],
        ),
    ]
