# Generated by Django 4.1.3 on 2022-11-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
